eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      leaseRenwalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2

    ribbon:
      eureka:
        enable: true
